//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWork1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class V_CUSLIST
    {
        public int CID { get; set; }
        [Display(Name="客戶名稱")]
        public string CNAME { get; set; }
        public string CNO { get; set; }
        public string CMAIL { get; set; }
        public string CTEL { get; set; }
        public string CFAX { get; set; }
        public string CADD { get; set; }
        [Display(Name="聯絡人數量")]
        public Nullable<int> CR { get; set; }
        [Display(Name = "銀行帳戶數量")]
        public Nullable<int> BR { get; set; }
    }
}
