//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWork1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class 客戶資料
    {
        public 客戶資料()
        {
            this.客戶聯絡人 = new HashSet<客戶聯絡人>();
            this.客戶銀行資訊 = new HashSet<客戶銀行資訊>();
        }
    
        public int Id { get; set; }

        [Required]
        public string 客戶名稱 { get; set; }
        [Required(ErrorMessage="統一編號長度為8碼!")]
        [StringLength(8), MinLength(8)]
        public string 統一編號 { get; set; }
        [Required]
        [RegularExpression(@"^\(?\d{2}\)?[\s\-]?\d{4}\-?\d{4}$", ErrorMessage="電話格式輸入錯誤!")]
        public string 電話 { get; set; }
        [Required]
        [RegularExpression(@"^\(?\d{2}\)?[\s\-]?\d{4}\-?\d{4}$", ErrorMessage = "電話格式輸入錯誤!")]
        public string 傳真 { get; set; }
        [Required]
        public string 地址 { get; set; }
        [Required]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Email輸入格式有誤!!")]
        public string Email { get; set; }
        public bool 是否已刪除 { get; set; }

        public virtual ICollection<客戶聯絡人> 客戶聯絡人 { get; set; }
        public virtual ICollection<客戶銀行資訊> 客戶銀行資訊 { get; set; }
    }
}
